package br.ufg.api.ocd.config.initialization;

import br.ufg.api.ocd.model.LocalDeAtendimento;

import java.util.HashSet;
import java.util.Set;

public class LocalAtendimentoInitialization {


    public static Set<LocalDeAtendimento> criaListaDeLocais(){
        Set<LocalDeAtendimento> listaDeLocais = new HashSet<>();
        listaDeLocais.add(new LocalDeAtendimento("Região campinas - centro","Distrito","Campinas - centro","Setor norte ferroviário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Região leste","Distrito","Leste","Jardim novo mundo","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Região noroeste","Distrito","Noroeste","Vila mutirão","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Região norte","Distrito","Norte","Jardim guanabara i","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Região oeste","Distrito","Oeste","Setor bairro goiá","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Distrito sudoeste","Distrito","Sudoeste","Setor sudoeste","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Região sul","Distrito","Sul","Jardim américa","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Amendoeiras","Cais","Leste","Setor parque das amendoeiras","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Bairro goiá","Cais","Oeste","Setor bairro goiá","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Campinas","Cais","Campinas/centro","Setor dos funcionários","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Cândida de morais","Cais","Noroeste","Setor cândida de morais","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Chácara do governador","Cais","Leste","Setor chácara do governador","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Deputado joão natal","Cais","Campinas/centro","Setor vila nova","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Finsocial","Cais","Noroeste","Setor finsocial","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim guanabara iii","Cais","Norte","Jardim guanabara iii","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim novo mundo","Cais","Leste","Jardim novo mundo","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim américa","Ciams","Sul","Jardim américa","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Novo horizonte","Ciams","Sudoeste","Novo horizonte","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Pedro ludovico","Ciams","Sul","Setor pedro ludovico","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Urias magalhães","Ciams","Norte","Setor urias magalhães","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("João batista de sousa júnior - upa itaipu","Upa","Sudoeste","Residencial itaipu","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Maria pires perillo - upa noroeste","Upa","Noroeste","Jardim curitiba i","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("“Benedito dos santos vieira” setor perim","Centros de saúde","Norte","Setor perim","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Cidade jardim (antigo rodoviário) - michele muniz do carmo","Centros de saúde","Campinas/centro","Setor cidade jardim","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Conjunto riviera","Centros de saúde","Leste","Jardim brasil","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Dr. Afonso h. Da s. E souza vila água branca","Centros de saúde","Leste","Setor água branca","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Esplanada do anicuns","Centros de saúde","Campinas/centro","Setor esplanada dos anincus","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Fama","Centros de saúde","Campinas/centro","Setor marechal rondon","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("“Hortência mendonça” - vila redenção","Centros de saúde","Sul","Vila redenção","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("“Isabel maria da silva” - vila maria dilce","Centros de saúde","Norte","Vila maria dilce","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim vila boa","Centros de saúde","Sudoeste","Vila boa","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jd. Balneário m. Ponte","Centros de saúde","Norte","Jardim balneário meia ponte","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("“José do egídio martins” - vila união","Centros de saúde","Sudoeste","Vila união","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("“Marinho lemos” – negrão de lima","Centros de saúde","Campinas/centro","Setor negrão de lima","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Norte ferroviário","Centros de saúde","Campinas/centro","Setor norte ferroviário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Parque amazônia","Centros de saúde","Sul","Parque amazônia","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Parque anhanguera","Centros de saúde","Sudoeste","Parque anhanguera","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Parque ind. João braz","Centros de saúde","Oeste","Parque ind. João braz","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Setor criméia leste","Centros de saúde","Campinas/centro","Setor criméia leste","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vila canaã","Centros de saúde","Campinas/centro","Vila canaã","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vila clemente","Centros de saúde","Norte","Vila clemente","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vila mauá","Centros de saúde","Sudoeste","Vila mauá","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vila moraes","Centros de saúde","Campinas/centro","Vila moraes","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vila santa helena","Centros de saúde","Campinas/centro","Vila paraíso","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Andréia cristina","Centro de saúde da família - csf","Sudoeste","Setor andréia cristina","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Antonio carlos pires","Centro de saúde da família - csf","Norte","Setor antonio carlos pires","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Aruanã iii","Centro de saúde da família - csf","Leste","Conjunto aruanã iii","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Bairro da vitória ii","Centro de saúde da família - csf","Noroeste","Bairro da vitória","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Bairro goiá","Centro de saúde da família - csf","Oeste","Setor bairro goiá","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Bairro são francisco","Centro de saúde da família - csf","Oeste","Bairro são francisco","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Barravento","Centro de saúde da família - csf","Noroeste","Residencial barravento","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Boa vista / floresta","Centro de saúde da família - csf","Noroeste","Bairro boa vista","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Buena vista","Centro de saúde da família - csf","Oeste","Residencial buena vista i","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Cachoeira dourada","Centro de saúde da família - csf","Norte","Jardim guanabara i","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Campus samambaia","Centro de saúde da família - csf","Norte","Campus samambaia","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Condomínio das esmeraldas","Centro de saúde da família - csf","Sudoeste","Condomínio das esmeraldas i","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Condomínio morada do sol","Centro de saúde da família - csf","Noroeste","Setor morada do sol","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Conjunto itatiaia","Centro de saúde da família - csf","Norte","Conjunto itatiaia i","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vera cruz i","Centro de saúde da família - csf","Oeste","Conjunto vera cruz i","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vera cruz ii","Centro de saúde da família - csf","Oeste","Vera cruz ii","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Criméia oeste","Centro de saúde da família - csf","Campinas/centro","Setor criméia oeste","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Distrito de vila rica","Centro de saúde da família - csf","Norte","Setor vila rica","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Dom fernando ii","Centro de saúde da família - csf","Leste","Jardim dom fernando ii","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Estrela dalva","Centro de saúde da família - csf","Noroeste","Setor estrela dalva","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Garavelo b","Centro de saúde da família - csf","Sudoeste","Setor garavelo b","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Grajaú","Centro de saúde da família - csf","Sudoeste","Setor grajaú","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim aroeira","Centro de saúde da família - csf","Leste","Jardim das aroeiras","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim caravelas","Centro de saúde da família - csf","Sudoeste","Jardim caravelas","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim colorado","Centro de saúde da família - csf","Noroeste","Setor jardim colorado","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("JARDIM CURITIBA I e II","CENTRO DE SAÚDE DA FAMÍLIA - CSF","NOROESTE","JARDIM CURITIBA II","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim curitiba iii","Centro de saúde da família - csf","Noroeste","Bairro boa vista","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim guanabara i","Centro de saúde da família - csf","Norte","Jardim guanabara","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim mariliza","Centro de saúde da família - csf","Leste","Jardim mariliza","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim mirabel","Centro de saúde da família - csf","Oeste","Setor bairro goiá","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim novo planalto","Centro de saúde da família - csf","Noroeste","Setor novo planalto","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim primavera","Centro de saúde da família - csf","Noroeste","Jardim primavera","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Jardim aritana","Centro de saúde da família - csf","Oeste","Jardim aritana","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Leste universitário","Centro de saúde da família - csf","Campinas/centro","Setor leste universitário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Madre germana ii","Centro de saúde da família - csf","Sudoeste","Conjunto habitacional madre germana ii","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Núcleo de apoio a saúde da familia - nasf curitiba i","Centro de saúde da família - csf","Noroeste","Jardim curitiba i","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Parque atheneu i","Centro de saúde da família - csf","Leste","Parque atheneu","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Parque dos buritis","Centro de saúde da família - csf","Oeste","Parque dos buritis","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Parque eldorado oeste","Centro de saúde da família - csf","Oeste","Parque eldorado oeste","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Parque santa rita","Centro de saúde da família - csf","Sudoeste","Parque santa rita","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Parque tremendão","Centro de saúde da família - csf","Noroeste","Parque tremendão","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Real conquista","Centro de saúde da família - csf","Sudoeste","Setor real conquista","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Militão rodrigues (antigo recanto das minas gerais)","Centro de saúde da família - csf","Leste","Jardim abapuru","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial brisa da mata","Centro de saúde da família - csf","Noroeste","Residencial brisa da mata","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial ana clara","Centro de saúde da família - csf","Sudoeste","Condomínio das esmeraldas","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial eli forte","Centro de saúde da família - csf","Sudoeste","Residencial eli forte","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial goiânia viva","Centro de saúde da família - csf","Oeste","Reserva ecologica do residencial goiânia viva","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial itaipu","Centro de saúde da família - csf","Sudoeste","Residencial itaipu","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial jardim do cerrado","Centro de saúde da família - csf","Oeste","Residencial jardim do cerrado 4","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial jardim do cerrado vi","Centro de saúde da família - csf","Oeste","Jardim do cerrado vi","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial vale dos sonhos","Centro de saúde da família - csf","Norte","Residencial vale dos sonhos","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial ville de france","Centro de saúde da família - csf","Leste","Residencial ville de france","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencial ytapuã","Centro de saúde da família - csf","Oeste","Residencial ytapuã","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("São carlos","Centro de saúde da família - csf","Noroeste","Bairro são carlos","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Setor luana park","Centro de saúde da família - csf","Oeste","Setor luana park","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Setor recanto do bosque","Centro de saúde da família - csf","Noroeste","Setor recanto do bosque","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Setor são judas tadeu","Centro de saúde da família - csf","Norte","Setor são judas tadeu","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Setor santo hilário","Centro de saúde da família - csf","Leste","Bairro santo hilário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vila mutirão","Centro de saúde da família - csf","Noroeste","Vila mutirão","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vf-18 - finsocial","Centro de saúde da família - csf","Noroeste","Vila finsocial","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vila pedroso","Centro de saúde da família - csf","Leste","Vila pedroso","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vila regina","Centro de saúde da família - csf","Oeste","Vila regina","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Ambulatório municipal de psiquiatria","Unidade de atendimento à saúde mental","Sul","Jardim américa","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial – caps noroeste/jardim liberdade","Unidade de atendimento à saúde mental","Noroeste","Vila mutirão","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial - caps beija-flor","Unidade de atendimento à saúde mental","Sudoeste","Jardim presidente","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial - caps esperança","Unidade de atendimento à saúde mental","Oeste","Jardim petropóles","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial - caps girassol","Unidade de atendimento à saúde mental","Campinas/centro","Setor campinas","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial - caps novo mundo","Unidade de atendimento à saúde mental","Leste","Jardim das aroeiras","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial - caps vida","Unidade de atendimento à saúde mental","Sul","Setor marista","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial - caps – ad/casa","Unidade de atendimento à saúde mental","Sul","Setor sul","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial infanto-juvenil – caps água viva","Unidade de atendimento à saúde mental","Sul","Setor vila nova","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de atenção psicossocial infanto juvenil - caps negrão de lima","Unidade de atendimento à saúde mental","Campinas/centro","Setor negrão de lima","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de convivencia cuca fresca","Unidade de atendimento à saúde mental","Sul","Jardim américa","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Pronto socorro psiquiátrico “wassily chuc”","Unidade de atendimento à saúde mental","Sul","Setor bueno","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residência terapêutica beija-flor i","Unidade de atendimento à saúde mental","Sudoeste","Setor faiçalville","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residência terapêutica beija-flor ii (unidade feminina)","Unidade de atendimento à saúde mental","Sudoeste","Setor faiçalville","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residência terapêutica mendanha i (unidade feminina)","Unidade de atendimento à saúde mental","Oeste","Jardim petropóles","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residência terapêutica mendanha ii (unidade masculina)","Unidade de atendimento à saúde mental","Oeste","Jardim petropóles","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residência terapêutica novo mundo i","Unidade de atendimento à saúde mental","Leste","Jardim novo mundo","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Residencia terapeutica novo mundo ii","Unidade de atendimento à saúde mental","Leste","Vila concordia","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Associação de trab. E prod. Solidária em saúde mental - gerarte i","Unidade de atendimento à saúde mental","Sul","Setor marista","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Unidade de trab. E prod. Solidária da saúde mental - gerarte ii","Unidade de atendimento à saúde mental","Campinas/centro","Setor dos funcionários","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de comercialização de economia solidária - loja arte e saúde","Unidade de atendimento à saúde mental","Sul","Setor aeroporto","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de referencia - crdt","Ceo - centro de especialidades odontológicas","Sul","Setor sul","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Cais jardim novo mundo","Ceo - centro de especialidades odontológicas","Campinas - centro","Jardim novo mundo","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Cais cândida de moraes","Ceo - centro de especialidades odontológicas","Campinas/centro","Vila moraes","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Ciams novo horizonte","Ceo - centro de especialidades odontológicas","Sudoeste","Novo horizonte","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Ambulatório municipal de queimaduras","Outras unidades","Campinas/centro","Setor dos funcionários","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vigilancia em saude do trabalhador","Outras unidades","Campinas/centro","Setor norte ferroviário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de referência em ortopedia e fisioterapia crof","Outras unidades","Campinas/centro","Setor aeroviário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro de referência em atenção à saúde da pessoa idosa - craspi","Outras unidades","Campinas/centro","Setor cidade jardim","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Crdt -“cândido j. S. De moura”","Outras unidades","Campinas/centro","Setor norte ferroviário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Vigilância em zoonoses","Outras unidades","Rural","Fazenda val das pombas, rodov. Go-020 km 05","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Farmácia de insumos e medicamentos especiais","Outras unidades","Campinas/centro","Vila viana","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Farmacia distrital central","Outras unidades","Campinas/centro","Setor norte ferroviário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Farmacia distrital oeste","Outras unidades","Oeste","Setor bairro goiá","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Farmacia popular/faculdade de farmacia da universidade federal de goiás - ufg","Outras unidades","Campinas/centro","Setor leste universitário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Farmacia popular do brasil","Outras unidades","Campinas/centro","Setor central","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Hospital da mulher e maternidade dona iris","Outras unidades","Sul","Vila redenção","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Maternidade nascer cidadão","Outras unidades","Noroeste","Jardim curitiba iii","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Ouvidoria da saúde","Outras unidades","Noroeste","Park lozandes","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Serviço de ver. De óbitos - svo","Outras unidades","Campinas/centro","Setor cidade jardim","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Serviço esp. Em eng. De segurança e em medicina do trabalho – sesmt","Outras unidades","Noroeste","Park lozandes","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Consultorio de rua","Outras unidades","Campinas/centro","Setor leste universitário","Goiânia"));
        listaDeLocais.add(new LocalDeAtendimento("Centro municipal de vacinação","Outras unidades","Sul","Setor pedro ludovico","Goiânia"));
        return listaDeLocais;
    }
}
