server:
  port: 9080

spring:
  data.mongodb:
    #uri: mongodb://ocd-docker-mongo:27017/ocd-cadastros
    host: ocd-docker-mongo
    port: 27017
    database: ocd-cadastros
    username: admin
    password: 123

logging:
  file: logs/java-mongo-docker-log